version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.0  # Specify the Terraform version you want
    commands:
      - echo Installing dependencies...
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Logging in to AWS...
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION

  build:
    commands:
      - echo Starting Terraform...
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan
      - opa eval --data policy.rego --input tfplan "data.example.allow"

  post_build:
    commands:
      - terraform apply -auto-approve tfplan
